from sqlalchemy import Column, BigInteger, String, Integer, Float, Boolean
from database.database import Base

class Order(Base):
    __tablename__ = "orders"

    ticket = Column(BigInteger, primary_key=True, index=True)
    login = Column(BigInteger)
    symbol = Column(String(20))
    comment = Column(String(255))
    external_id = Column(String(64))
    time_setup = Column(BigInteger)           
    type = Column(String(64))
    state = Column(String(20))
    time_expiration = Column(BigInteger)      
    time_done = Column(BigInteger)            
    time_setup_msc = Column(BigInteger)       
    time_done_msc = Column(BigInteger)        
    type_filling = Column(String(20))
    type_time = Column(String(20))
    magic = Column(BigInteger)
    reason = Column(String(20))
    position_id = Column(BigInteger)
    position_by_id = Column(BigInteger)
    volume_initial = Column(Float)
    volume_current = Column(Float)
    price_open = Column(Float)
    price_current = Column(Float)
    price_stoplimit = Column(Float)
    sl = Column(Float)
    tp = Column(Float)

class Deal(Base):
    __tablename__ = "deals"

    ticket = Column(BigInteger, primary_key=True, index=True)
    login = Column(BigInteger)
    order = Column(BigInteger)
    position_id = Column(BigInteger)
    time = Column(BigInteger)              
    time_msc = Column(BigInteger)          
    type = Column(String(64))
    entry = Column(String(20))
    magic = Column(BigInteger)
    reason = Column(String(20))
    volume = Column(Float)
    price = Column(Float)
    commission = Column(Float)
    swap = Column(Float)
    profit = Column(Float)
    fee = Column(Float)
    sl = Column(Float)
    tp = Column(Float)
    symbol = Column(String(20))
    comment = Column(String(255))
    external_id = Column(String(64))

class Position(Base):
    __tablename__ = "positions"

    ticket = Column(BigInteger, primary_key=True, index=True)
    login = Column(BigInteger)
    identifier = Column(BigInteger, index=True)
    time = Column(BigInteger)                 
    time_msc = Column(BigInteger)             
    time_update = Column(BigInteger)          
    time_update_msc = Column(BigInteger)      
    type = Column(String(64))
    magic = Column(BigInteger)
    reason = Column(String(20))
    volume = Column(Float)
    price_open = Column(Float)
    sl = Column(Float)
    tp = Column(Float)
    price_current = Column(Float)
    swap = Column(Float)
    xprofit = Column(Float)
    symbol = Column(String(20))
    comment = Column(String(255))
    external_id = Column(String(64))

class Account(Base):
    __tablename__ = "accounts"

    login = Column(BigInteger, primary_key=True, index=True)
    trade_mode = Column(String(20))
    leverage = Column(Integer)
    limit_orders = Column(Integer)
    margin_so_mode = Column(String(20))
    trade_allowed = Column(Boolean)
    trade_expert = Column(Boolean)
    margin_mode = Column(String(20))
    currency_digits = Column(Integer)
    fifo_close = Column(Boolean)
    hedge_allowed = Column(Boolean)
    balance = Column(Float)
    credit = Column(Float)
    profit = Column(Float)
    equity = Column(Float)
    margin = Column(Float)
    margin_free = Column(Float)
    margin_level = Column(Float)
    margin_so_call = Column(Float)
    margin_so_so = Column(Float)
    margin_initial = Column(Float)
    margin_maintenance = Column(Float)
    assets = Column(Float)
    liabilities = Column(Float)
    commission_blocked = Column(Float)
    name = Column(String(128))
    server = Column(String(128))
    currency = Column(String(16))
    company = Column(String(128))
